"""added description to sub recipe

Revision ID: 2e504f90d6e7
Revises: 4608fe4af2fb
Create Date: 2021-10-19 20:48:10.346878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e504f90d6e7'
down_revision = '4608fe4af2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_recipes', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_recipes', 'description')
    # ### end Alembic commands ###
